### ISSUE TITLE
Migliorare la descrizione del repo

### ISSUE THREAD

**Issue by marcoaimo** [todotoit/git-blondies#1]
Ho imbastito una prima bozza di spiegazione del repo che verrà utilizzato per il corso GITHUB FOR BLONDES.
https://github.com/todotoit/git-blondies/blob/master/README.md

**Comment by michellenebiolo** [comment]
Dici qui?
https://github.com/todotoit/git-blondies/commit/1004afd36943a54bfa5fe4507de47e10e980e9cf#diff-04c6e90faac2675aa89e2176d2eec7d8R3

**Comment by marcoaimo** [comment]
Direi di si 👍
